### ISSUE TITLE
[Feature Request]: Dark mode

### ISSUE THREAD

**Issue by sof202** [EpigeneticsExeter/EpigenomicsLabWeb#25]
### Details

Have a button somewhere that can turn the pages to a dark mode option

This has very low priority

**Comment by sof202** [comment]
Here's how you could do it (there might be better ways):

[medium article](https://david-x.medium.com/light-mode-dark-mode-dynamic-theming-through-scss-mixin-c86e57a4de49)

## Themes

You'd create some theme names with particular values you want to change:

```css
$themes: (
  light: (
    text: #333333,
    bg: #ffffff,
    brand: #567567,
  ),
  dark: (
    text: #ffffff,
    bg: #333333,
    brand: #abcabc,
  ),
);
```


## Holy mixin

You'd make a mixin that works like a map:

```css
@mixin themify($themes) {
  @each $name, $values in $themes {
    .#{$name}-theme {
      $theme-map: $values !global;
      @content;
    }
  }
}
@function themed($key) {
  @return map-get($theme-map, $key);
}
```

## You can then use this in your other sass files with:

```css
p {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    border-width: 10px;
    border-radius: 10px;
    width: 50px;
    height: 50px;
    transition: smooth;
}
@include themify($themes) {
    p {
        color: themed('text');
        background-color: themed('bg');
    }
};
```

## JS

From here all you need is some simple js to set the top level element's class to the name of the theme. (So change between `theme-light` and `theme-dark` for the example above)
