### ISSUE TITLE
[Feature Request]: Add blog page navigation

### ISSUE THREAD

**Issue by sof202** [EpigeneticsExeter/EpigenomicsLabWeb#68]
### Details

Using

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
```

in hugo.toml. You can get ids for each heading of a blog post.

You could then use this to create a side bar that allows you to jump around the blog to different sections.
